/*Crea un procedimiento que obtiene en una variable Stotal la suma de los ingresos correspondientes a los 3  ingresos mas caros  obtenidos en una consulta */
USE clinica2021;

DELIMITER ||
CREATE DEFINER=`root`@`localhost` PROCEDURE `INGRESOS_MAS_CAROS`()
BEGIN
	DECLARE COSTE_TOTAL FLOAT DEFAULT 0;
	DECLARE COSTE_ACTUAL FLOAT DEFAULT 0;
	DECLARE N INT DEFAULT 0;
	DECLARE  CURSOR1 CURSOR FOR SELECT COSTE FROM INGRESOS ORDER BY COSTE DESC;
		OPEN CURSOR1;
		WHILE N < 3 DO
			FETCH CURSOR1 INTO COSTE_ACTUAL;
				SET COSTE_TOTAL = COSTE_TOTAL + COSTE_ACTUAL;
			SET N = N + 1;
		END WHILE;
	SELECT COSTE_TOTAL;
	END||
DELIMITER ;
    


SELECT COSTE FROM INGRESOS ORDER BY COSTE DESC;


/*NUMERO TOTAL DIAS QUE SE PASA UN PACIENTE INGRESADO/*/
DELIMITER ||
CREATE PROCEDURE N_TOTAL_DIAS_PACIENTE (IN PACIENTE VARCHAR (2))
BEGIN
	DECLARE DIAS_TOTAL INT DEFAULT 0;
    DECLARE N_DIAS FLOAT DEFAULT 0;
    DECLARE VAR_FINAL INT DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VAR_FINAL =1;
    DECLARE CURSOR1 CURSOR FOR SELECT  datediff(FECHA_INGRESO, FECHA_ALTA)  FROM INGRESOS I, PACIENTES P
    WHERE I.COD_PACIENTE = P.COD_PACIENTE AND PACIENTE = COD_PACIENTE;
		OPEN CURSOR1;
        BUCLE: LOOP
			FETCH CURSOR1 INTO DIAS_TOTAL;
            if VAR_FINAL = 1 THEN LEAVE BUCLE;
		END LOOP;
END ||

DELIMITER ;
    /*Metes dos provincias, calcula el coste total de cada una y las guarda en una tabla. Usando cursores sino no vale*/
    DELIMITER ||
    CREATE PROCEDURE COSTE_PROVINCIAS (IN PROVINCIA1 VARCHAR(60), IN PROVINCIA2 varchar(60))
    BEGIN
		DECLARE done INT DEFAULT FALSE;
		DECLARE COSTE_PROVINCIA1 FLOAT DEFAULT 0;
		DECLARE COSTE_PROVINCIA2 FLOAT DEFAULT 0;
        DECLARE COSTE_TOTAL1 FLOAT DEFAULT 0;
        DECLARE COSTE_TOTAL2 FLOAT DEFAULT 0;
        DECLARE CURSOR1 CURSOR FOR SELECT COSTE FROM INGRESOS, PACIENTES WHERE PROVINCIA = PROVINCIA1;
        DECLARE CURSOR2 CURSOR FOR SELECT COSTE FROM INGRESOS, PACIENTES WHERE PROVINCIA = PROVINCIA2;
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
		
        OPEN CURSOR1;
		OPEN CURSOR2;
		read_loop: LOOP
        FETCH CURSOR1 INTO COSTE_PROVINCIA1;
		FETCH CURSOR2 INTO COSTE_PROVINCIA2;
        IF done THEN
		LEAVE read_loop;
        ELSE DO COSTE_TOTAL1 = COSTE_PROVINCIA1 + COSTE_TOTAL1;
			DO COSTE_TOTAL2 = COSTE_PROVINCIA2 + COSTE_TOTAL2;
		END IF;
        END LOOP;
        CLOSE CURSOR1;
        CLOSE CURSOR2;
        END ||
	DELIMITER ;

    
    
    
    
    
    
    
    
    
    