use empresamy2;

CREATE TABLE PRUEBA (
COD INT,
APELLIDO1 VARCHAR (10),
SALARIO_TOTAL FLOAT,
PRIMARY KEY (COD)
) engine=InnoDB;

DELIMITER ||

CREATE PROCEDURE INGRESAR_DATOS()
BEGIN
DECLARE done INT DEFAULT FALSE;
DECLARE SALARIO_PLUS FLOAT DEFAULT 0;
DECLARE CODIGO_EMPLE INT DEFAULT 0;
DECLARE SALARIO_BASE FLOAT DEFAULT 0;
DECLARE NOMBRE VARCHAR (10);
DECLARE SOBRESUELDO FLOAT DEFAULT 0;
DECLARE CUR1 CURSOR FOR SELECT APELLIDO, SALARIO, COMISION FROM EMPLE;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
	OPEN CUR1;
		HOLA:LOOP
			FETCH CUR1 INTO NOMBRE, SALARIO_BASE, SOBRESUELDO;
				IF done THEN LEAVE HOLA;
				ELSE 
					IF SOBRESUELDO IS NULL THEN 
						SET SOBRESUELDO = 0;
						SET SALARIO_PLUS = SALARIO_BASE + SOBRESUELDO;
                        SET CODIGO_EMPLE = CODIGO_EMPLE + 1;
                        INSERT INTO PRUEBA (COD, APELLIDO1, SALARIO_TOTAL) VALUES (CODIGO_EMPLE, NOMBRE, SALARIO_PLUS);
                        
                        ELSE 
						SET SALARIO_PLUS = SALARIO_BASE + SOBRESUELDO;
						SET CODIGO_EMPLE = CODIGO_EMPLE + 1;
						INSERT INTO PRUEBA (COD, APELLIDO1, SALARIO_TOTAL) VALUES (CODIGO_EMPLE, NOMBRE, SALARIO_PLUS);
					END IF;
				END IF;
		END LOOP;
	CLOSE CUR1;
END ||

DELIMITER ;


use empresamy2;



/*Escribir un procedimiento que modifique la localidad de un departamento. El procedimiento recibirá como parámetros el número del departamento y la localidad nueva.*/
/*cREA UN PROCEDIMIENTO QUE ME META UN CODIGO DE EMPLEADO SEGUN EL DEPARTAMENTO QUE ES A LA NUEVA TABLA*/




/*Calcular la comisión mas el salario (previamente debe comprobar que tiene comisión), si es así
 realizará el calculo y lo insertara en una nueva columna de la tabla( salrio mas comisión),*/

 
 
 ALTER TABLE EMPLE ADD SALARIO_TOTAL float;
 
 
 
 
 DELIMITER ||

CREATE PROCEDURE NUEVA_COLUMNA()
BEGIN
DECLARE done INT DEFAULT FALSE;
DECLARE SALARIO_PLUS FLOAT DEFAULT 0;
DECLARE SALARIO_BASE FLOAT DEFAULT 0;
DECLARE SOBRESUELDO FLOAT DEFAULT 0;
DECLARE CUR1 CURSOR FOR SELECT  SALARIO, COMISION FROM EMPLE;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
	OPEN CUR1;
		HOLA:LOOP
			FETCH CUR1 INTO SALARIO_BASE, SOBRESUELDO;
				IF done THEN LEAVE HOLA;
				ELSE 
					SET SALARIO_PLUS = 0;
					IF SOBRESUELDO IS NULL THEN SET SOBRESUELDO = 0;
						SET SALARIO_PLUS = SALARIO_BASE + SOBRESUELDO;
                        INSERT INTO EMPLE (SALARIO_TOTAL) VALUES (SALARIO_PLUS);
                        UPDATE EMPLE SET SALARIO_TOTAL = SALARIO_PLUS;
                        
                        ELSE 
						SET SALARIO_PLUS = SALARIO_BASE + SOBRESUELDO;
						UPDATE EMPLE SET SALARIO_TOTAL = SALARIO_PLUS;
					END IF;
				END IF;
		END LOOP;
	CLOSE CUR1;
END ||

DELIMITER ;

 
 /*Crea el procedimiento que se pase el nombre de un paciente y si existe se introduce en una tabla nueva donde 
 vengan el numero total de ingresos, si no existe saldra por pantalla no existe*/
 
USE CLINICA2021; 
 
 CREATE TABLE PACIENTE_N_INGRESOS (
 COD_PACIENTE VARCHAR(2),
 NOMBRE VARCHAR(20),
 TOTAL_INGRESO FLOAT,
 PRIMARY KEY (COD_PACIENTE),
 foreign key (COD_PACIENTE) REFERENCES PACIENTES (COD_PACIENTE)
 );
 
 
 DELIMITER ||
 
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERTAR_TABLA_N_INGRESOS`(IN COD_PACIENTE1 INT)
BEGIN
DECLARE NOMBRE1 VARCHAR (20) DEFAULT ' ';
DECLARE NUMERO FLOAT DEFAULT 0;
DECLARE DONE INT DEFAULT FALSE;
DECLARE CUR1 CURSOR FOR SELECT NOMBRE, COUNT(COD_INGRESO) FROM PACIENTES P, INGRESOS I 
WHERE P.COD_PACIENTE = COD_PACIENTE1 AND P.COD_PACIENTE = I.COD_PACIENTE GROUP BY NOMBRE;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;

	IF COD_PACIENTE1 IN (SELECT COD_PACIENTE FROM PACIENTES) 
    THEN
		OPEN CUR1;
			RW:LOOP
				FETCH CUR1 INTO NOMBRE1, NUMERO;
					IF DONE THEN LEAVE RW;
                    ELSE
						IF COD_PACIENTE1 IN (SELECT COD_PACIENTE FROM paciente_n_ingresos) THEN
							UPDATE PACIENTE_N_INGRESOS SET TOTAL_INGRESO = NUMERO WHERE COD_PACIENTE1 = COD_PACIENTE; 
						ELSE 
							INSERT INTO paciente_n_ingresos VALUES (COD_PACIENTE1, NOMBRE1, NUMERO);
						END IF;
					END IF;
			END LOOP;
		CLOSE CUR1;
	ELSE SELECT CONCAT('El paciente', COD_PACIENTE1, 'no existe');
    END IF;
 
 END||
 
 DELIMITER ;
 
 
 
 
 
 