/*Crea un procedimiento que obtiene en una variable Stotal la suma de los ingresos correspondientes a los 3  ingresos mas caros  obtenidos en una consulta */
USE clinica2021;

DELIMITER ||
CREATE DEFINER=`root`@`localhost` PROCEDURE `INGRESOS_MAS_CAROS`()
BEGIN
	DECLARE COSTE_TOTAL FLOAT DEFAULT 0;
	DECLARE COSTE_ACTUAL FLOAT DEFAULT 0;
	DECLARE N INT DEFAULT 0;
	DECLARE  CURSOR1 CURSOR FOR SELECT COSTE FROM INGRESOS ORDER BY COSTE DESC;
		OPEN CURSOR1;
		WHILE N < 3 DO
			FETCH CURSOR1 INTO COSTE_ACTUAL;
				SET COSTE_TOTAL = COSTE_TOTAL + COSTE_ACTUAL;
			SET N = N + 1;
		END WHILE;
	SELECT COSTE_TOTAL;
	END||
DELIMITER ;
    
	

SELECT COSTE FROM INGRESOS ORDER BY COSTE DESC;


/*NUMERO TOTAL DIAS QUE SE PASA UN PACIENTE INGRESADO/*