/*Crea un procedimiento que obtiene en una variable Stotal la suma de los ingresos correspondientes a los 3  ingresos mas caros  obtenidos en una consulta */
USE clinica2021;

DELIMITER ||
CREATE DEFINER=`root`@`localhost` PROCEDURE `INGRESOS_MAS_CAROS`()
BEGIN
	DECLARE COSTE_TOTAL FLOAT DEFAULT 0;
	DECLARE COSTE_ACTUAL FLOAT DEFAULT 0;
	DECLARE N INT DEFAULT 0;
	DECLARE  CURSOR1 CURSOR FOR SELECT COSTE FROM INGRESOS ORDER BY COSTE DESC;
		OPEN CURSOR1;
		WHILE N < 3 DO
			FETCH CURSOR1 INTO COSTE_ACTUAL;
				SET COSTE_TOTAL = COSTE_TOTAL + COSTE_ACTUAL;
			SET N = N + 1;
		END WHILE;
	SELECT COSTE_TOTAL;
	END||
DELIMITER ;
    
	

SELECT COSTE FROM INGRESOS ORDER BY COSTE DESC;


/*NUMERO TOTAL DIAS QUE SE PASA UN PACIENTE INGRESADO/*/
DELIMITER ||
CREATE PROCEDURE N_TOTAL_DIAS_PACIENTE (IN PACIENTE VARCHAR (2))
BEGIN
	DECLARE DIAS_TOTAL INT DEFAULT 0;
    DECLARE N_DIAS FLOAT DEFAULT 0;
    DECLARE VAR_FINAL INT DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VAR_FINAL =1;
    DECLARE CURSOR1 CURSOR FOR SELECT  datediff(FECHA_INGRESO, FECHA_ALTA)  FROM INGRESOS I, PACIENTES P
    WHERE I.COD_PACIENTE = P.COD_PACIENTE AND PACIENTE = COD_PACIENTE;
		OPEN CURSOR1;
        BUCLE: LOOP
			FETCH CURSOR1 INTO DIAS_TOTAL;
            if VAR_FINAL = 1 THEN LEAVE BUCLE;
		END LOOP
END ||

    
    
    
    
    
    
    
    
    
    
    
    