
create database camiones;
use camiones;


CREATE TABLE CAMION  (
CODCAMION INT AUTO_INCREMENT,
POTENCIA VARCHAR (50) NOT NULL,
MODELO varchar (50) NOT NULL,
PRIMARY KEY (CODCAMION)
) ENGINE InnoDB;

CREATE TABLE CAMIONERO  (
CODCAMIONERO INT AUTO_INCREMENT,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO varchar (50) NOT NULL,
CARNET_CONDUCIR varchar(8) UNIQUE,
PRIMARY KEY (CODCAMIONERO)
) ENGINE InnoDB;

CREATE TABLE CAMIONERO_CAMION (
CODCAMIONERO INT ,
CODCAMION INT ,
FECHA date,
PRIMARY KEY (CODCAMIONERO, CODCAMION, FECHA),
FOREIGN KEY (CODCAMIONERO) References CAMIONERO (CODCAMIONERO),
FOREIGN KEY (CODCAMION) References CAMION (CODCAMION)
) ENGINE InnoDB;

CREATE TABLE PAQUETE (
CODPAQUETE INT AUTO_INCREMENT,
DESCRIPCION VARCHAR (50) NOT NULL,
DIRECCION varchar (50) NOT NULL,
CODCIUDAD INT,
CODCAMIONERO INT,
PRIMARY KEY (CODPAQUETE),
FOREIGN KEY (CODCIUDAD) REFERENCES CIUDAD (CODCIUDAD),
FOREIGN KEY (CODCAMIONERO) REFERENCES CAMIONERO (CODCAMIONERO)
) ENGINE InnoDB;











