

CREATE TABLE IES (
CODCENTRO varchar(3),
NOMBRE VARCHAR (10) NOT NULL,
UBICACION VARCHAR (20) NOT NULL,
Localidad VARCHAR(50),
PRIMARY KEY (CODCENTRO)
) ENGINE InnoDB;

CREATE TABLE ALUMNO (
N_EXP VARCHAR(8),
NOMBRE VARCHAR(40),
APELLIDO VARCHAR(40),
DIRECCIÓN VARCHAR (50),
Primary key (N_EXP)
);

CREATE TABLE CICLOS (
CODCICLO VARCHAR (8),
NOMBRE VARCHAR (10) NOT NULL,
NIVEL VARCHAR (8) NOT NULL,
HORAS TINYINT,
PRIMARY KEY (CODCICLO)
);

CREATE TABLE IES_CICLOS (
CODCENTRO varchar(3),
CODCICLO VARCHAR (8),
TURNOS VARCHAR(18),
PRIMARY KEY (CODCENTRO, CODCICLO),
FOREIGN KEY (CODCENTRO) REFERENCES IES (CODCENTRO),
FOREIGN KEY (CODCICLO) REFERENCES CICLO (CODCICLO)
) ENGINE InnoDB;

CREATE TABLE CICLOS_ALUMNO (
CODALUMNO varchar(3),
CODCICLO VARCHAR (8),
AÑO date,
NOTA_FINAL INT,
primary key (AÑO, CODCICLO, CODALUMNO),
FOREIGN KEY (CODALUMNO) REFERENCES ALUMNO (CODCALUMNO),
FOREIGN KEY (CODCICLO) REFERENCES CICLO (CODCICLO)
) ENGINE InnoDB;
