CREATE TABLE TRASLADO(
CODTRASLADO INT,
CODPRODUCTOR INT,
CODRESIDUO INT,
CODCONSTITUYENTE INT,
CODTRANSPORTE INT,
CODSEGURO INT,
PARTE_DE_RESIDUO INT NOT NULL,
PRIMARY KEY (CODTRASLADO),
FOREIGN KEY (CODPRODUCTOR, CODRESIDUO) REFERENCES RESIDUO (CODPRODUCTOR, CODRESIDUO),
FOREIGN KEY (CODTRANSPORTE) REFERENCES EMPRESA_TRANSPORTE(CODTRANSPORTE),
FOREIGN KEY (CODSEGURO) REFERENCES LUGAR_SEGURO (CODSEGURO)
) ENGINE InnoDB;





