COCHES:
mat (matricula del coche, 8 caracteres y llave primaria)
marca (15 caracteres)
an_fab (año de fabricacion, número de 2 dígitos)

MECANICOS:
dni (9 caracteres, llave primaria)
nombre (15 caracteres)
puesto (15 caracteres)
parcial (1 caracter)

TRABAJOS:
mat (la matrícula del coche, llave externa respecto de COCHES),
dni (el dni del mecánico),
horas (número de 3 cifras con 1 decimal, debe ser mayor de 0.5)
fecha_rep (tipo fecha)

CREATE DATABASE COCHES;
USE COCHES;
CREATE TABLE COCHES(
MAT VARCHAR (5),
MARCA VARCHAR (15),
AN_FAB VARCHAR (2),
CONSTRAINT COCHES PRIMARY KEY (MAT)
)ENGINE = INNODB;

CREATE TABLE MECANICOS(
DNI VARCHAR (9),
NOMBRE VARCHAR (15),
PUESTO VARCHAR (15),
PARCIAL VARCHAR (1),
CONSTRAINT MECANICOS primary key (DNI)
) ENGINE = INNODB;

CREATE TABLE TRABAJOS(
COD_TRABAJO VARCHAR (4),
MAT VARCHAR (5),
DNI VARCHAR (9),
HORAS tinyint (10),
fecha_rep date,
CONSTRAINT  PRIMARY KEY (COD_TRABAJO),
CONSTRAINT FOREIGN KEY (MAT) REFERENCES COCHES(MAT),
CONSTRAINT FOREIGN KEY (DNI) REFERENCES MECANICOS(DNI)
) ENGINE= INNODB;

ALTER TABLE COCHES ADD COLUMN MODELO VARCHAR (15);

ALTER TABLE COCHES MODIFY COLUMN MAT VARCHAR (7);
ALTER TABLE COCHES MODIFY COLUMN AN_FAB VARCHAR (4);

INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('M3020KY', 'TOYOTA', 'CARINA', 2016);
INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('A3020KA', 'RENAULT', 'MEGANE ', 2017);
INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('B3020KB', 'RENAULT ', '5', 2017);
INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('C3020KC', 'PEUGEOT ', '504', 2018);
INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('D3020KD', 'PEUGEOT ', '504', 2018);
INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('E3020KE', 'BEATTLE ', '207', 2019);
INSERT INTO coches (mat, marca, modelo, AN_FAB) VALUES ('H3020KH', 'TOYOTA', 'CARINA', 2016);


INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('1111', 'ANTONIO', 'MOTOR', '1');
INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('2222 ', 'ANTONIO', 'MOTOR', '1');
INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('3333', 'ANTONIO', 'MOTOR', '1');
INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('4444', 'ANTONIO', 'MOTOR', '1');
INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('5555', 'ANTONIO', 'MOTOR', '1');
INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('6666', 'ANTONIO', 'MOTOR', '1');
INSERT INTO MECANICOS (DNI, NOMBRE, PUESTO, PARCIAL) VALUES ('7777', 'ANTONIO', 'MOTOR', '1');



