SELECT COD_FAMILIA, DESCRIPCION FROM ies_elena.familiaprofesional;

SELECT DENOMINACION FROM CICLOSFP, FAMILIAPROFESIONAL
WHERE ciclosfp.cod_familia = '0001' and
CICLOSFP.COD_FAMILIA = FAMILIAPROFESIONAL.COD_FAMILIA;

SELECT DESCRIPCION FROM MODULOS M, CICLOSFP C, CICLOSFPMODULOS I
WHERE I.COD_CICLO = C.COD_CICLO
AND M.COD_MODULO = I.COD_MODULO
AND (C.denominacion = 'ASIR' OR C.DENOMINACION = 'DAW');

SELECT * FROM CICLOSFP
WHERE DURACION > '1000';

SELECT DENOMINACION FROM CICLOSFP C, FAMILIAPROFESIONAL F
WHERE C.DURACION > '1000' AND F.DESCRIPCION = 'informatica'
AND (C.COD_FAMILIA = F.COD_FAMILIA);


SELECT DENOMINACION, DURACION +100 FROM CICLOSFP C, FAMILIAPROFESIONAL F
WHERE C.DURACION > '1000' AND F.DESCRIPCION = 'informatica'
AND (C.COD_FAMILIA = F.COD_FAMILIA);

SELECT NOMBRE FROM IES I
WHERE I.LOCALIDAD = 'Alcorcón';

SELECT DESCRIPCION FROM FAMILIAPROFESIONAL
WHERE COD_FAMILIA NOT IN (SELECT COD_FAMILIA FROM CICLOSFP);