SELECT COD_FAMILIA, DESCRIPCION FROM ies_elena.familiaprofesional;

SELECT DENOMINACION FROM CICLOSFP, FAMILIAPROFESIONAL
WHERE ciclosfp.cod_familia = '0001' and
CICLOSFP.COD_FAMILIA = FAMILIAPROFESIONAL.COD_FAMILIA;

SELECT DESCRIPCION FROM MODULOS M, CICLOSFP C, CICLOSFPMODULOS I
WHERE I.COD_CICLO = C.COD_CICLO
AND M.COD_MODULO = I.COD_MODULO
AND (C.COD_CICLO = '0001' OR C.COD_CICLO = '0002');